language: node_js
node_js:
  - 12
  - 10
  - 8
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
deploy:
  provider: npm
  email: guy@cornelius.dev
  api_key: $NPM_API_KEY
  on:
    tags: true
